### ISSUE TITLE
Add BigWigs Packager

### ISSUE THREAD

**Issue by srhinos** [Vloer/keycount#1]
Would love if you could add the bigwigs packager to this repo! This'll let people who don't use Curseforge download from github (and potentially save you time by uploading releases to CF / Wago as well!)

I'm happy to submit a PR for this if you'd like, though you'll have to add a github token to the repo's secrets so it can be used for packaging!

**Comment by Vloer** [comment]
Hey, sorry for the late reply. Im kinda busy atm so feel free to submit the PR, if you need anything from me (like token) just let me know and i'll help you out. Thanks:)
