### ISSUE TITLE
S4 Day 1 data missing

### ISSUE THREAD

**Issue by rideekulous** [Vloer/keycount#14]
Data is missing for the dozen or so dungeons on S4 reset before your S4 commit was pushed. Should that data be accessible? Mine is not showing anything.

![image](https://github.com/Vloer/keycount/assets/165203372/f2c78a33-8e4e-45c5-9c4d-d0861591f0e4)

**Comment by Vloer** [comment]
Probably has to do with reset date since release is different for us/eu. Can you check if the data is completely missing or just missing when the current season check is enabled?

**Comment by rideekulous** [comment]
The data is completely missing, or at least not showing in the addon. I remember seeing the "started recording" messages as I was running.

![image](https://github.com/Vloer/keycount/assets/165203372/fac84049-18dc-4a58-8df5-4b5df8841f2c)

**Comment by Vloer** [comment]
Seems that the current season button broke. Ill fix it tomorrow

**Comment by rideekulous** [comment]
Thanks for fixing this, I was able to do a regex find/replace (NP++) to fix the dungeons I ran before your update.

FIND: `(2024-04-23.*(\r\n.*){4}\r\n[^-]*)-3`
REPLACE: `\1-4`

**Comment by Vloer** [comment]
Good to hear, you could've done it manually but helps being a software engineer i guess
