### ISSUE TITLE
double info message "no dungeons stored"

### ISSUE THREAD

**Issue by swixfort** [Vloer/keycount#16]
After a clean install on load the addon displays the message "KeyCount: No dungeons stored!" two times:
![image](https://github.com/user-attachments/assets/82411000-db48-4d23-bc9a-aef9916ff764)
This is because in KeyCount.lua the following methods are called in "KeyCount:InitSelf:
```lua
    C_Timer.After(2, KeyCount.InitDatabase)
    C_Timer.After(3, KeyCount.InitPlayerList)
```
In both Init-Methods the message "KeyCount:GetStoredDungeons()" will be called which is the source of the message.

**Comment by Vloer** [comment]
Fixed in v0.10.6-beta
