### ISSUE TITLE
KeyCount-v0.4.2 - Error

### ISSUE THREAD

**Issue by mavrck48** [Vloer/keycount#2]
Seeing the following errors on v0.4.2.  Hope this helps.

2x KeyCount/KeyCount.lua:129: attempt to index global 'KeyCountDB' (a nil value)
[string "@KeyCount/KeyCount.lua"]:129: in function `InitDungeon'
[string "@KeyCount/KeyCount.lua"]:110: in function `CheckIfInDungeon'
[string "@KeyCount/KeyCount.lua"]:30: in function `?'
[string "@KeyCount/KeyCount.lua"]:7: in function <KeyCount/KeyCount.lua:6>

Locals:
self = KeyCount {
 PLAYER_LOGOUT = <function> defined @KeyCount/KeyCount.lua:10
 AddDungeonEvents = <function> defined @KeyCount/KeyCount.lua:68
 ADDON_LOADED = <function> defined @KeyCount/KeyCount.lua:19
 CHALLENGE_MODE_START = <function> defined @KeyCount/KeyCount.lua:33
 RemoveDungeonEvents = <function> defined @KeyCount/KeyCount.lua:75
 SetKeyStart = <function> defined @KeyCount/KeyCount.lua:139
 GROUP_ROSTER_UPDATE = <function> defined @KeyCount/KeyCount.lua:50
 SaveAndReset = <function> defined @KeyCount/KeyCount.lua:228
 InitDungeon = <function> defined @KeyCount/KeyCount.lua:116
 CheckIfInDungeon = <function> defined @KeyCount/KeyCount.lua:105
 SetKeyEnd = <function> defined @KeyCount/KeyCount.lua:181
 ZONE_CHANGED_NEW_AREA = <function> defined @KeyCount/KeyCount.lua:27
 InitSelf = <function> defined @KeyCount/KeyCount.lua:88
 SaveDungeons = <function> defined @KeyCount/KeyCount.lua:238
 mapInfo = <table> {
 }
 OnEvent = <function> defined @KeyCount/KeyCount.lua:6
 SetTimeToComplete = <function> defined @KeyCount/KeyCount.lua:211
 0 = <userdata>
 CHALLENGE_MODE_COMPLETED = <function> defined @KeyCount/KeyCount.lua:39
 SetKeyFailed = <function> defined @KeyCount/KeyCount.lua:171
 CheckIfKeyFailed = <function> defined @KeyCount/KeyCount.lua:161
 FinishDungeon = <function> defined @KeyCount/KeyCount.lua:200
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @KeyCount/KeyCount.lua:57
 GROUP_LEFT = <function> defined @KeyCount/KeyCount.lua:43
}
keystoneStillRunning = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'KeyCountDB' (a nil value)"

**Comment by Vloer** [comment]
This should be fixed in v0.4.3
