### ISSUE TITLE
Export option [feature request]

### ISSUE THREAD

**Issue by ninthwalker** [Vloer/keycount#3]
I know you are still ironing out bugs, but if you have time for additional features down the line, it would be awesome if you could build in an export to csv type option. Would allow us to save a copy offline or save multiple seasons for review/stats. 

Thanks again for the addon.

**Comment by Vloer** [comment]
Wow addons don't have the ability to create files (would allow malware to be distributed etc). The only option is to generate a popup of which you can copy all the data and manually import it into a csv or something. I'll look into adding this.

**Comment by ninthwalker** [comment]
Right, I realize that. I use a guild export addon (for ref: https://github.com/CruelDrool/GuildRosterExport)
And it does similar with a pop-up to copy from. So that would be fine I think. 

I go a step farther and have code that reads the export that is saved to the savedvariables for automated alrerts, so I don't even have to copy/paste, but even just the pop-up I think would be cool.

**Comment by Vloer** [comment]
Implemented in latest release

**Comment by ninthwalker** [comment]
Just wanted to say thanks! Works great, and is nice to be able to do additional analytics on the data for our keys that way.
